// Generated by CIRCT firtool-1.128.0
module ACG(
  input  reset,
         In_0_Req,
  output In_0_Ack,
  input  In_1_Req,
  output In_1_Ack,
         Out_0_Req,
  input  Out_0_Ack,
  output fire_o
);

  wire _fire_o_Dfire_Z;
  wire _full_wire_PRO_Dreq_1_Z;
  wire _full_wire_PRO_Dreq_Z;
  reg  full_wire_PRO_ff;
  reg  full_wire_PRO_ff_1;
  reg  empty_wire_PRO_ff;
  always @(posedge _fire_o_Dfire_Z or posedge reset) begin
    if (reset) begin
      full_wire_PRO_ff <= 1'h0;
      full_wire_PRO_ff_1 <= 1'h0;
      empty_wire_PRO_ff <= 1'h0;
    end
    else begin
      full_wire_PRO_ff <= In_0_Req;
      full_wire_PRO_ff_1 <= In_1_Req;
      empty_wire_PRO_ff <= ~Out_0_Ack;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (reset) begin
        full_wire_PRO_ff = 1'h0;
        full_wire_PRO_ff_1 = 1'h0;
        empty_wire_PRO_ff = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  DelayElement #(
    .DelayValue(5)
  ) full_wire_PRO_Dreq (
    .I (In_0_Req),
    .Z (_full_wire_PRO_Dreq_Z)
  );
  DelayElement #(
    .DelayValue(5)
  ) full_wire_PRO_Dreq_1 (
    .I (In_1_Req),
    .Z (_full_wire_PRO_Dreq_1_Z)
  );
  DelayElement #(
    .DelayValue(1)
  ) fire_o_Dfire (
    .I
      ((full_wire_PRO_ff ^ _full_wire_PRO_Dreq_Z)
       & (full_wire_PRO_ff_1 ^ _full_wire_PRO_Dreq_1_Z)
       & (Out_0_Ack ^ ~empty_wire_PRO_ff)),
    .Z (_fire_o_Dfire_Z)
  );
  assign In_0_Ack = full_wire_PRO_ff;
  assign In_1_Ack = full_wire_PRO_ff_1;
  assign Out_0_Req = empty_wire_PRO_ff;
  assign fire_o = _fire_o_Dfire_Z;
endmodule

