// Generated by CIRCT firtool-1.128.0
module ADD(
  input        clock,
               reset,
               io_In0_HS_Req,
  output       io_In0_HS_Ack,
  input  [7:0] io_In0_Data,
  input        io_In1_HS_Req,
  output       io_In1_HS_Ack,
  input  [7:0] io_In1_Data,
  output       io_Out_HS_Req,
  input        io_Out_HS_Ack,
  output [7:0] io_Out_Data
);

  wire       _ACG_fire_o;
  reg  [7:0] io_Out_Data_REG;
  always @(posedge _ACG_fire_o)
    io_Out_Data_REG <= io_In0_Data + io_In1_Data;
  ACG ACG (
    .reset     (reset),
    .In_0_Req  (io_In0_HS_Req),
    .In_0_Ack  (io_In0_HS_Ack),
    .In_1_Req  (io_In1_HS_Req),
    .In_1_Ack  (io_In1_HS_Ack),
    .Out_0_Req (io_Out_HS_Req),
    .Out_0_Ack (io_Out_HS_Ack),
    .fire_o    (_ACG_fire_o)
  );
  assign io_Out_Data = io_Out_Data_REG;
endmodule

