// Generated by CIRCT firtool-1.128.0
module Sync_MatMul(
  input         clock,
                reset,
  input  [7:0]  io_A_0,
                io_A_1,
                io_A_2,
                io_A_3,
                io_B_0,
                io_B_1,
                io_B_2,
                io_B_3,
  input         io_start,
  output [15:0] io_C_0,
                io_C_1,
                io_C_2,
                io_C_3,
                io_C_4,
                io_C_5,
                io_C_6,
                io_C_7,
                io_C_8,
                io_C_9,
                io_C_10,
                io_C_11,
                io_C_12,
                io_C_13,
                io_C_14,
                io_C_15
);

  reg [15:0] acc_0;
  reg [15:0] acc_1;
  reg [15:0] acc_2;
  reg [15:0] acc_3;
  reg [15:0] acc_4;
  reg [15:0] acc_5;
  reg [15:0] acc_6;
  reg [15:0] acc_7;
  reg [15:0] acc_8;
  reg [15:0] acc_9;
  reg [15:0] acc_10;
  reg [15:0] acc_11;
  reg [15:0] acc_12;
  reg [15:0] acc_13;
  reg [15:0] acc_14;
  reg [15:0] acc_15;
  reg [7:0]  aPipe_0;
  reg [7:0]  aPipe_1;
  reg [7:0]  aPipe_2;
  reg [7:0]  aPipe_4;
  reg [7:0]  aPipe_5;
  reg [7:0]  aPipe_6;
  reg [7:0]  aPipe_8;
  reg [7:0]  aPipe_9;
  reg [7:0]  aPipe_10;
  reg [7:0]  aPipe_12;
  reg [7:0]  aPipe_13;
  reg [7:0]  aPipe_14;
  reg [7:0]  bPipe_0;
  reg [7:0]  bPipe_1;
  reg [7:0]  bPipe_2;
  reg [7:0]  bPipe_3;
  reg [7:0]  bPipe_4;
  reg [7:0]  bPipe_5;
  reg [7:0]  bPipe_6;
  reg [7:0]  bPipe_7;
  reg [7:0]  bPipe_8;
  reg [7:0]  bPipe_9;
  reg [7:0]  bPipe_10;
  reg [7:0]  bPipe_11;
  always @(posedge clock) begin
    if (reset) begin
      acc_0 <= 16'h0;
      acc_1 <= 16'h0;
      acc_2 <= 16'h0;
      acc_3 <= 16'h0;
      acc_4 <= 16'h0;
      acc_5 <= 16'h0;
      acc_6 <= 16'h0;
      acc_7 <= 16'h0;
      acc_8 <= 16'h0;
      acc_9 <= 16'h0;
      acc_10 <= 16'h0;
      acc_11 <= 16'h0;
      acc_12 <= 16'h0;
      acc_13 <= 16'h0;
      acc_14 <= 16'h0;
      acc_15 <= 16'h0;
      aPipe_0 <= 8'h0;
      aPipe_1 <= 8'h0;
      aPipe_2 <= 8'h0;
      aPipe_4 <= 8'h0;
      aPipe_5 <= 8'h0;
      aPipe_6 <= 8'h0;
      aPipe_8 <= 8'h0;
      aPipe_9 <= 8'h0;
      aPipe_10 <= 8'h0;
      aPipe_12 <= 8'h0;
      aPipe_13 <= 8'h0;
      aPipe_14 <= 8'h0;
      bPipe_0 <= 8'h0;
      bPipe_1 <= 8'h0;
      bPipe_2 <= 8'h0;
      bPipe_3 <= 8'h0;
      bPipe_4 <= 8'h0;
      bPipe_5 <= 8'h0;
      bPipe_6 <= 8'h0;
      bPipe_7 <= 8'h0;
      bPipe_8 <= 8'h0;
      bPipe_9 <= 8'h0;
      bPipe_10 <= 8'h0;
      bPipe_11 <= 8'h0;
    end
    else begin
      acc_0 <= io_start ? 16'h0 : acc_0 + {8'h0, io_A_0} * {8'h0, io_B_0};
      acc_1 <= io_start ? 16'h0 : acc_1 + {8'h0, aPipe_0} * {8'h0, io_B_1};
      acc_2 <= io_start ? 16'h0 : acc_2 + {8'h0, aPipe_1} * {8'h0, io_B_2};
      acc_3 <= io_start ? 16'h0 : acc_3 + {8'h0, aPipe_2} * {8'h0, io_B_3};
      acc_4 <= io_start ? 16'h0 : acc_4 + {8'h0, io_A_1} * {8'h0, bPipe_0};
      acc_5 <= io_start ? 16'h0 : acc_5 + {8'h0, aPipe_4} * {8'h0, bPipe_1};
      acc_6 <= io_start ? 16'h0 : acc_6 + {8'h0, aPipe_5} * {8'h0, bPipe_2};
      acc_7 <= io_start ? 16'h0 : acc_7 + {8'h0, aPipe_6} * {8'h0, bPipe_3};
      acc_8 <= io_start ? 16'h0 : acc_8 + {8'h0, io_A_2} * {8'h0, bPipe_4};
      acc_9 <= io_start ? 16'h0 : acc_9 + {8'h0, aPipe_8} * {8'h0, bPipe_5};
      acc_10 <= io_start ? 16'h0 : acc_10 + {8'h0, aPipe_9} * {8'h0, bPipe_6};
      acc_11 <= io_start ? 16'h0 : acc_11 + {8'h0, aPipe_10} * {8'h0, bPipe_7};
      acc_12 <= io_start ? 16'h0 : acc_12 + {8'h0, io_A_3} * {8'h0, bPipe_8};
      acc_13 <= io_start ? 16'h0 : acc_13 + {8'h0, aPipe_12} * {8'h0, bPipe_9};
      acc_14 <= io_start ? 16'h0 : acc_14 + {8'h0, aPipe_13} * {8'h0, bPipe_10};
      acc_15 <= io_start ? 16'h0 : acc_15 + {8'h0, aPipe_14} * {8'h0, bPipe_11};
      aPipe_0 <= io_start ? 8'h0 : io_A_0;
      aPipe_1 <= io_start ? 8'h0 : aPipe_0;
      aPipe_2 <= io_start ? 8'h0 : aPipe_1;
      aPipe_4 <= io_start ? 8'h0 : io_A_1;
      aPipe_5 <= io_start ? 8'h0 : aPipe_4;
      aPipe_6 <= io_start ? 8'h0 : aPipe_5;
      aPipe_8 <= io_start ? 8'h0 : io_A_2;
      aPipe_9 <= io_start ? 8'h0 : aPipe_8;
      aPipe_10 <= io_start ? 8'h0 : aPipe_9;
      aPipe_12 <= io_start ? 8'h0 : io_A_3;
      aPipe_13 <= io_start ? 8'h0 : aPipe_12;
      aPipe_14 <= io_start ? 8'h0 : aPipe_13;
      bPipe_0 <= io_start ? 8'h0 : io_B_0;
      bPipe_1 <= io_start ? 8'h0 : io_B_1;
      bPipe_2 <= io_start ? 8'h0 : io_B_2;
      bPipe_3 <= io_start ? 8'h0 : io_B_3;
      bPipe_4 <= io_start ? 8'h0 : bPipe_0;
      bPipe_5 <= io_start ? 8'h0 : bPipe_1;
      bPipe_6 <= io_start ? 8'h0 : bPipe_2;
      bPipe_7 <= io_start ? 8'h0 : bPipe_3;
      bPipe_8 <= io_start ? 8'h0 : bPipe_4;
      bPipe_9 <= io_start ? 8'h0 : bPipe_5;
      bPipe_10 <= io_start ? 8'h0 : bPipe_6;
      bPipe_11 <= io_start ? 8'h0 : bPipe_7;
    end
  end // always @(posedge)
  assign io_C_0 = acc_0;
  assign io_C_1 = acc_1;
  assign io_C_2 = acc_2;
  assign io_C_3 = acc_3;
  assign io_C_4 = acc_4;
  assign io_C_5 = acc_5;
  assign io_C_6 = acc_6;
  assign io_C_7 = acc_7;
  assign io_C_8 = acc_8;
  assign io_C_9 = acc_9;
  assign io_C_10 = acc_10;
  assign io_C_11 = acc_11;
  assign io_C_12 = acc_12;
  assign io_C_13 = acc_13;
  assign io_C_14 = acc_14;
  assign io_C_15 = acc_15;
endmodule
